# Generated by Django 4.2.1 on 2023-05-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Men_Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Men_Joggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Men_Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Men_Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Women_Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Women_Joggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Women_Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Women_Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_jacket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.women_jacket')),
                ('women_joggers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.women_joggers')),
                ('women_pants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.women_pants')),
                ('women_shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.women_shirt')),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mens_jacket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.men_jacket')),
                ('mens_joggers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.men_joggers')),
                ('mens_pants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.men_pants')),
                ('mens_shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.men_shirt')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.earring')),
                ('glasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.glasses')),
                ('necklace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.necklace')),
            ],
        ),
    ]
